global.newMaterialParts = [
	/////////////// Tier 0 Metals: Overworld /////////////////////////////
	//'allomancy' 提示来自百科镕金术介绍 https://www.mcmod.cn/class/4713.html
	//'feruchemy' 提示来自百科藏金术介绍 https://www.mcmod.cn/class/8984.html

	{
		material: 'iron',
		ore_name: '铁',
		color: 0xd9d7d7,
		type: 'base_metal',
		tier: 0,
		itemParts: ['plating', 'sheet'],
		blockParts: ['cog_block'],
		fluid_id: 'tconstruct:molten_iron',
		ore: true,
		byproducts: ['nickel'],
		allomancy: '指示周围所有金属，右击可将自己向前靠近',
		feruchemy: '轻掠 - 存储重量  抽取：减速+防御增加  存储：摔落保护',
	},
	{
		material: 'tin',
		ore_name: '锡',
		color: 0x9dbdc2,
		type: 'base_metal',
		tier: 0,
		itemParts: ['rod', 'wire'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_tin',
		ore: true,
		byproducts: ['flourite'],
		allomancy: '锡可以提供夜视功能，并能通过指示粒子看到声音来自哪个方向。这个粒子还会根据声源的敌意染上不同的颜色。友好的小怪是绿色的，敌对的小怪是红色的',
		feruchemy: '风语 - 存储五感  抽取：夜视  存储：失明',
	},
	{
		material: 'gold',
		ore_name: '金',
		color: 0xf5c564,
		type: 'base_metal',
		tier: 0,
		itemParts: ['plating'],
		blockParts: ['cog_block'],
		fluid_id: 'tconstruct:molten_gold',
		ore: true,
		byproducts: ['iron'],
		allomancy: '指示当前维度上次死亡位置',
		feruchemy: '制血者 - 存储健康  抽取：再生/瞬间治疗',
	},
	{
		material: 'copper',
		ore_name: '铜',
		color: 0xfc9d65,
		type: 'base_metal',
		tier: 0,
		itemParts: ['interlocking_component', 'plating', 'sheet'],
		blockParts: ['cog_block'],
		fluid_id: 'tconstruct:molten_copper',
		ore: true,
		byproducts: ['gold', 'sulfur'],
		allomancy: '让自身其他金属单位对于其他玩家不可见',
		feruchemy: '库藏 - 存储记忆  抽取：保存经验值，存储：释放保存的经验值。',
	},

	/////////////// Tier 1 Metals: Nether/Overworld /////////////////////////////
	{
		material: 'lead',
		ore_name: '铅',
		color: 0x4f5a6e,
		type: 'base_metal',
		tier: 1,
		itemParts: ['rod', 'sheet'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_lead',
		ore: true,
		byproducts: ['silver'],
	},
	{
		material: 'silver',
		ore_name: '银',
		color: 0xc7d3d6,
		type: 'base_metal',
		tier: 1,
		itemParts: ['rod', 'wire', 'sheet'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_silver',
		ore: true,
		byproducts: ['lead'],
	},
	{
		material: 'zinc',
		ore_name: '锌',
		color: 0x97c7b3,
		type: 'base_metal',
		tier: 1,
		itemParts: ['plate', 'gear', 'rod', 'wire'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_zinc',
		ore: true,
		byproducts: ['sulfur'],
		allomancy: '锌可以暴乱怪物的情绪，使其产生敌意。这意味着它们会攻击附近的任何东西。甚至农场动物也会成为威胁',
		feruchemy: '星火 - 存储思考速度  抽取：获得相较正常情况下而言更多的经验球  存储：获得相对平时而言更少的经验球',
	},
	{
		material: 'arcanite',
		ore_name: '奥金',
		color: 0xe2d4fa,
		tier: 1,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
	},

	/////////////// Tier 2 Metals /////////////////////////////
	{
		material: 'cobalt',
		ore_name: '钴',
		color: 0x2e5cd1,
		type: 'base_metal',
		tier: 2,
		itemParts: [
			'plate',
			'gear',
			'rod',
			'wire',
			'interlocking_component',
			'model_spool',
			'model_wire_coil',
			'reinforced_plating',
			'sheet',
			'hull_panel',
			'plating',
		],
		blockParts: ['cog_block', 'casing', 'coil'],
		ore: true,
		fluid_id: 'tconstruct:molten_cobalt',
		byproducts: ['gold', 'mithril'],
	},
	{
		material: 'aluminum',
		ore_name: '铝',
		color: 0xb6c2c2,
		type: 'base_metal',
		tier: 2,
		itemParts: ['plate', 'gear', 'rod', 'plating', 'sheet'],
		blockParts: [],
		ore: true,
		raw_ore: true,
		fluid_id: 'tconstruct:molten_aluminum',
		byproducts: ['titanium'],
		allomancy: '清除自己所有的金属单位和药水效果（即刻生效）',
		feruchemy: '真我 - 存储身份  储存在金属意识中的铝会为你 "锁定"，只有你才能使用其中储存的能量',
	},
	{
		material: 'mithril',
		ore_name: '秘银',
		color: 0x8a90db,
		tier: 2,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
		fluid: 'thick',
		fluid_id: 'kubejs:molten_mithril',
	},

	{
		material: 'nickel',
		ore_name: '镍',
		color: 0xc2b17a,
		type: 'base_metal',
		tier: 2,
		itemParts: ['rod', 'wire', 'sheet'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_nickel',
		ore: true,
		byproducts: ['iron', 'platinum'],
	},

	/////////////// Tier 3 Metals: The End /////////////////////////////

	{
		material: 'titanium',
		ore_name: '钛',
		color: 0x4668cf,
		type: 'base_metal',
		tier: 3,
		itemParts: ['plate', 'gear', 'rod', 'plating', 'bolt'],
		blockParts: ['casing', 'scaffolding', 'frame_box'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_titanium',
		ore: true,
		raw_ore: true,
		byproducts: ['aluminum'],
	},
	{
		material: 'rune',
		ore_name: '符石',
		color: 0x73b4bf,
		type: 'base_metal',
		tier: 3,
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'uranium',
		ore_name: '铀',
		color: 0x8be8b0,
		type: 'base_metal',
		tier: 3,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		ore: true,
		fluid_id: 'tconstruct:molten_uranium',
		byproducts: ['lead', 'thorium'],
	},
	{
		material: 'magnesium',
		ore_name: '镁',
		color: 0xcfc5d4,
		tier: 3,
		type: 'base_metal',
		itemParts: ['plate', 'gear', 'rod', 'plating'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},

	{
		material: 'netherite_scrap',
		ore_name: '下界合金',
		color: 0x543f35,
		tier: 3,
		type: 'base_metal',
		itemParts: ['dust'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_debris',
	},
	/////////////// Tier 4 Metals: Moon /////////////////////////////

	{
		material: 'osmium',
		ore_name: '锇',
		color: 0xe6f7ff,
		type: 'base_metal',
		tier: 4,
		itemParts: ['plate', 'gear', 'rod', 'plating'],
		blockParts: ['cog_block'],
		ore: true,
		byproducts: ['silver', 'platinum', 'manganese'],
	},
	{
		material: 'platinum',
		ore_name: '铂',
		color: 0x91ecff,
		type: 'base_metal',
		tier: 4,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block', 'cog_block'],
		ore: true,
		raw_ore: true,
		byproducts: ['nickel', 'osmium', 'chromium'],
	},
	{
		material: 'desh',
		ore_name: '戴斯',
		color: 0xffa34d,
		type: 'base_metal',
		tier: 4,
		itemParts: ['gear', 'rod', 'dust', 'wire', 'model_spool', 'model_wire_coil'],
		blockParts: ['coil'],
		ore: true,
	},
	{
		material: 'cadmium',
		ore_name: '镉',
		color: 0x97b7bf,
		type: 'base_metal',
		tier: 4,
		itemParts: ['plate', 'gear', 'rod', 'dust'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		allomancy: '降低玩家周围怪物的速度，同时获得缓降效果',
		feruchemy: '喘息 - 存储呼吸  抽取：水下呼吸/水肺  存储：不在水中时出现氧气条',
		ore: true,
	},

	/////////////// Tier 5 Metals: Mars /////////////////////////////

	{
		material: 'stellarite',
		ore_name: '陨石',
		color: 0x858f7c,
		tier: 5,
		type: 'base_metal',
		itemParts: ['ingot', 'gear', 'rod', 'dust', 'plating'],
		blockParts: [],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'tungsten',
		ore_name: '钨',
		color: 0x282c33,
		type: 'base_metal',
		tier: 5,
		itemParts: [
			'plate',
			'gear',
			'rod',
			'plating',
			'reinforced_plating',
			'wire',
			'model_spool',
			'model_wire_coil',
		],
		blockParts: ['coil'],
		ore: true,
		raw_ore: true,
		byproducts: ['thorium'],
	},
	{
		material: 'orichalcum',
		ore_name: '山铜',
		color: 0xfa6837,
		tier: 5,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
		fluid: 'thick',
		fluid_id: 'kubejs:molten_orichalcum',
	},
	{
		material: 'ostrum',
		ore_name: '紫金',
		color: 0x73485d,
		tier: 5,
		type: 'base_metal',
		itemParts: ['gear', 'rod', 'dust', 'plate'],
		blockParts: [],
		ore: true,
	},

	/////////////// Tier 6 Metals: Venus /////////////////////////////
	{
		material: 'iridium',
		ore_name: '铱',
		color: 0x1942bf,
		type: 'base_metal',
		tier: 6,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},
	{
		material: 'palladium',
		ore_name: '钯',
		color: 0x4f2237,
		type: 'base_metal',
		tier: 6,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},
	{
		material: 'adamantium',
		ore_name: '精金',
		color: 0xc23c3c,
		tier: 6,
		type: 'base_metal',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'gear',
			'rod',
			'wire',
			'model_spool',
			'model_wire_coil',
		],
		blockParts: ['storage_block', 'coil'],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'calorite',
		ore_name: '耐热金属',
		color: 0xc43b3b,
		tier: 6,
		type: 'base_metal',
		itemParts: ['gear', 'rod', 'dust', 'plate'],
		blockParts: [],
		ore: true,
	},

	/////////////// Tier 7 Metals: Glacio /////////////////////////////
	{
		material: 'vibranium',
		ore_name: '振金',
		color: 0x7cebbe,
		tier: 7,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust', 'wire', 'model_spool', 'model_wire_coil'],
		blockParts: ['storage_block', 'coil'],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'uru',
		ore_name: '乌鲁',
		color: 0x1c121c,
		tier: 7,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
		fluid: 'thick',
		fluid_id: 'kubejs:molten_uru',
	},
	{
		material: 'draconium',
		ore_name: '龙',
		color: 0x421c63,
		tier: 7,
		type: 'base_metal',
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		raw_ore: true,
		fluid: 'thick',
		fluid_id: 'kubejs:molten_draconium',
	},
	///////////////// Tier 8 Metals: Glacio /////////////////////////////

	/////////////// Rare Metals /////////////////////////////
	{
		material: 'thorium',
		ore_name: '钍',
		color: 0x452852,
		type: 'base_metal',
		tier: 2,
		itemParts: ['plate', 'rod', 'gear'],
		blockParts: [],
		ore: true,
		raw_ore: true,
		byproducts: ['lead'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_thorium',
	},
	{
		material: 'manganese',
		ore_name: '锰',
		color: 0xb5c7a1,
		type: 'rare_metal',
		tier: 4,
		itemParts: [],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},
	{
		material: 'chromium',
		ore_name: '铬',
		color: 0xcfb793,
		type: 'rare_metal',
		tier: 4,
		itemParts: ['plate', 'gear', 'rod', 'dust'],
		blockParts: [],
		fluid: 'thick',
		allomancy: '激活后点击其他玩家，清除其药水效果和所有金属单位',
		feruchemy: '旋转 - 存储运气  抽取：运气增加  存储：运气下降',
		ore: true,
	},
	{
		material: 'lithium',
		ore_name: '锂',
		color: 0xab4154,
		type: 'rare_metal',
		tier: 5,
		itemParts: ['plating'],
		blockParts: [],
	},
	{
		material: 'molybdenum',
		ore_name: '钼',
		color: 0x78c4b6,
		type: 'rare_metal',
		tier: 5,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},
	{
		material: 'boron',
		ore_name: '硼',
		color: 0x20293b,
		tier: 5,
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		fluid: 'thick',
	},
	{
		material: 'scandium',
		ore_name: '钪',
		color: 0xd4d2bc,
		type: 'rare_metal',
		tier: 6,
		itemParts: [],
		blockParts: [],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'vanadium',
		ore_name: '钒',
		color: 0x464e66,
		type: 'rare_metal',
		tier: 7,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		ore: true,
		raw_ore: true,
	},
	{
		material: 'neodymium',
		ore_name: '钕',
		color: 0x634d59,
		type: 'rare_metal',
		tier: 7,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
	},

	/////////////// Tier 1 Alloys: Create Mixer /////////////////////////////
	{
		material: 'bronze',
		ore_name: '青铜',
		color: 0xfa7532,
		type: 'alloy',
		tier: 1,
		itemParts: ['rod', 'wire', 'sheet', 'plating'],
		blockParts: ['sheetmetal', 'cog_block', 'casing'],
		fluid_id: 'tconstruct:molten_bronze',
		amount: 4,
		dust_input: ['3x #forge:dusts/copper', '#forge:dusts/tin'],
		ingot_input: ['3x #forge:ingots/copper', '#forge:ingots/tin'],
		tinkers_input: [
			{ tag: 'forge:molten_copper', amount: 270 },
			{ tag: 'forge:molten_tin', amount: 90 },
		],
		allomancy: '检测其他玩家的金属',
		feruchemy: '哨兵 - 存储清醒  抽取：重置幻翼生成计时器；使世界时间入夜或日出  存储：生成幻翼（但是必须在计时器时间内全程存储）',
	},
	{
		material: 'electrum',
		ore_name: '琥珀金',
		color: 0xe6db95,
		type: 'alloy',
		tier: 1,
		itemParts: ['plating', 'model_wire_coil', 'sheet'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_electrum',
		amount: 2,
		dust_input: ['#forge:dusts/silver', '#forge:dusts/gold'],
		ingot_input: ['#forge:ingots/silver', '#forge:ingots/gold'],
		tinkers_input: [
			{ tag: 'forge:molten_gold', amount: 90 },
			{ tag: 'forge:molten_silver', amount: 90 },
		],
		allomancy: '指示当前维度重生点。（仅主世界和下界> 1.16 有效）',
		feruchemy: '顶峰 - 存储决心  抽取：获得额外的心（伤害吸收）  存储：停止自然恢复生命值',
	},
	{
		material: 'brass',
		ore_name: '黄铜',
		color: 0xffc96b,
		type: 'alloy',
		tier: 1,
		itemParts: ['gear', 'wire', 'dust', 'plating'],
		blockParts: ['cog_block', 'casing'],
		fluid_id: 'tconstruct:molten_brass',
		amount: 3,
		dust_input: ['2x #forge:dusts/copper', '#forge:dusts/zinc'],
		ingot_input: ['2x #forge:ingots/copper', '#forge:ingots/zinc'],
		tinkers_input: [
			{ tag: 'forge:molten_copper', amount: 180 },
			{ tag: 'forge:molten_zinc', amount: 90 },
		],
		allomancy: '使周围敌对生物变为被动生物',
		feruchemy: '火灵 - 存储温暖  抽取：熔化冰和雪，所有攻击附带火焰附加效果  存储：火焰保护',
	},
	{
		material: 'red_alloy',
		ore_name: '红石合金',
		color: 0xff2626,
		type: 'alloy',
		tier: 1,
		itemParts: [
			'plate',
			'gear',
			'wire',
			'dust',
			'rod',
			'model_spool',
			'model_wire_coil',
			'model_dual_coil',
		],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_red_alloy',
		amount: 2,
		dust_input: ['#forge:dusts/copper', '3x #forge:dusts/redstone'],
		ingot_input: ['#forge:ingots/copper', '3x #forge:dusts/redstone'],
		tinkers_input: [
			{ tag: 'forge:molten_copper', amount: 90 },
			{ tag: 'forge:redstone', amount: 300 },
		],
	},
	{
		material: 'pewter',
		ore_name: '白镴',
		color: 0x9d96b5,
		type: 'alloy',
		tier: 1,
		itemParts: ['dust'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_pewter',
		amount: 4,
		dust_input: ['2x #forge:dusts/tin', '#forge:dusts/silver', '#forge:dusts/lead'],
		ingot_input: ['2x #forge:ingots/tin', '#forge:ingots/silver', '#forge:ingots/lead'],
		tinkers_input: [
			{ tag: 'forge:molten_tin', amount: 180 },
			{ tag: 'forge:molten_silver', amount: 90 },
			{ tag: 'forge:molten_lead', amount: 90 },
		],
		allomancy: '获得跳跃提升 II ，速度，急迫 II 效果，同时可以使用巨人之刃',
		feruchemy: '蛮力 - 存储力量  抽取：急迫/力量  存储：虚弱/挖掘疲劳',
	},
	{
		material: 'auric_gold',
		ore_name: '叶金',
		color: 0xf2f274,
		type: 'alloy',
		tier: 1,
		itemParts: ['ingot', 'dust', 'nugget'],
		blockParts: ['storage_block'],
		amount: 1,
		dust_input: ['#forge:dusts/arcanite', '2x naturesaura:gold_powder'],
		ingot_input: ['#forge:ingots/arcanite', '2x naturesaura:gold_powder'],
	},
	//{
	//  'material': 'cast_iron',
	// ore_name: '铸铁',
	//  'color': 0x454545,
	//  'type': 'alloy',
	//  'tier': 1,
	//  'itemParts': ['ingot', 'nugget', 'plate', 'rod', 'gear'],
	//  'blockParts': ['storage_block'],
	//},
	{
		material: 'dielectric_alloy',
		ore_name: '绝缘合金',
		color: 0x2b2b2b,
		tier: 1,
		type: 'alloy',
		itemParts: ['ingot', 'dust', 'gear', 'plate'],
		blockParts: ['scaffolding'],
		dust_input: ['#forge:dusts/red_alloy', '2x powah:dielectric_paste'],
		ingot_input: ['#forge:ingots/red_alloy', '2x powah:dielectric_paste'],
		amount: 2,
	},

	{
		material: 'drenched_iron',
		ore_name: '烙铁',
		color: 0xb1f0fc,
		tier: 1,
		type: 'magic_alloy',
		itemParts: ['rod', 'gear', 'plate', 'dust'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_drenched_iron',
	},

	/////////////// Tier 2 Alloys: Tinkers or chapter 2 /////////////////////////////

	{
		material: 'constantan',
		ore_name: '康铜',
		color: 0xe8a156,
		type: 'alloy',
		tier: 2,
		itemParts: ['rod', 'wire', 'plating', 'model_spool', 'model_wire_coil', 'sheet'],
		blockParts: ['cog_block', 'coil'],
		fluid_id: 'tconstruct:molten_constantan',
		amount: 2,
		dust_input: ['#forge:dusts/copper', '#forge:dusts/nickel'],
		ingot_input: ['#forge:ingots/copper', '#forge:ingots/nickel'],
		tinkers_input: [
			{ tag: 'forge:molten_copper', amount: 90 },
			{ tag: 'forge:molten_nickel', amount: 90 },
		],
	},
	{
		material: 'invar',
		ore_name: '殷钢',
		color: 0xa4bab5,
		type: 'alloy',
		tier: 2,
		itemParts: ['rod', 'wire', 'plating', 'sheet'],
		blockParts: ['scaffolding', 'cog_block', 'casing', 'sheetmetal'],
		fluid_id: 'tconstruct:molten_invar',
		amount: 3,
		dust_input: ['2x #forge:dusts/iron', '#forge:dusts/nickel'],
		ingot_input: ['2x #forge:ingots/iron', '#forge:ingots/nickel'],
		tinkers_input: [
			{ tag: 'forge:molten_iron', amount: 180 },
			{ tag: 'forge:molten_nickel', amount: 90 },
		],
	},
	{
		material: 'rose_gold',
		ore_name: '玫瑰金',
		color: 0xffccd8,
		tier: 2,
		type: 'alloy',
		itemParts: ['dust', 'plate', 'gear', 'rod', 'wire'],
		blockParts: [],
		dust_input: ['#forge:dusts/gold', '#forge:dusts/copper'],
		ingot_input: ['#forge:ingots/gold', '#forge:ingots/copper'],
		amount: 2,
		fluid_id: 'tconstruct:molten_rose_gold',
		tinkers_input: [
			{ tag: 'forge:molten_gold', amount: 90 },
			{ tag: 'forge:molten_copper', amount: 90 },
		],
	},
	{
		material: 'amethyst_bronze',
		ore_name: '紫水晶青铜',
		color: 0xc58bc9,
		tier: 2,
		type: 'alloy',
		itemParts: ['dust', 'plate', 'gear', 'rod'],
		blockParts: [],
		dust_input: ['#forge:dusts/bronze', '#forge:gems/amethyst'],
		ingot_input: ['#forge:ingots/bronze', '#forge:gems/amethyst'],
		amount: 2,
		fluid_id: 'tconstruct:molten_amethyst_bronze',
		tinkers_input: [
			{ tag: 'forge:molten_bronze', amount: 90 },
			{ tag: 'tconstruct:molten_amethyst', amount: 100 },
		],
	},
	{
		material: 'steel',
		ore_name: '钢',
		color: 0xb5b3b3,
		type: 'alloy',
		tier: 2,
		fluid_id: 'tconstruct:molten_steel',
		itemParts: ['plate', 'gear', 'rod', 'sheet'],
		blockParts: ['casing'],
		amount: 1,
		tinkers_input: [
			{ tag: 'forge:molten_iron', amount: 90 },
			{ name: 'kubejs:molten_carbon', amount: 90 },
		],
		allomancy: '指示周围所有金属，右击可将自己向后远离',
		feruchemy: '钢奔 - 存储速度  抽取：速度  存储：缓慢',
	},
	{
		material: 'energetic_alloy',
		ore_name: '充能合金',
		color: 0xff874f,
		type: 'alloy',
		tier: 2,
		itemParts: [
			'custom_ingot',
			'dust',
			'nugget',
			'plate',
			'gear',
			'rod',
			'wire',
			'interlocking_component',
			'plating',
			'sheet',
			'bolt',
		],
		blockParts: ['storage_block', 'scaffolding', 'frame_box'],
		amount: 1,
		dust_input: ['#forge:dusts/electrum', 'kubejs:energetic_blend'],
		ingot_input: ['#forge:ingots/electrum', 'kubejs:energetic_blend'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_energetic_alloy',
	},
	{
		material: 'vinteum',
		ore_name: '温特姆',
		color: 0x9be3fa,
		type: 'alloy',
		tier: 2,
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_vinteum',
	},

	{
		material: 'hepatizon',
		ore_name: '黑色科林斯青铜',
		color: 0x5e497a,
		type: 'alloy',
		tier: 2,
		fluid_id: 'tconstruct:molten_hepatizon',
		amount: 2,
		dust_input: [
			'2x #forge:dusts/copper',
			'#forge:dusts/cobalt',
			'4x #forge:gems/quartz',
		],
		ingot_input: [
			'2x #forge:ingots/copper',
			'#forge:ingots/cobalt',
			'4x #forge:gems/quartz',
		],
		tinkers_input: [
			{ tag: 'forge:molten_copper', amount: 180 },
			{ tag: 'forge:molten_cobalt', amount: 90 },
			{ tag: 'tconstruct:molten_quartz', amount: 400 },
		],
		itemParts: [
			'plate',
			'gear',
			'rod',
			'dust',
			'interlocking_component',
			'wire',
			'plating',
		],
		blockParts: ['casing'],
	},
	{
		material: 'duralumin',
		ore_name: '硬铝',
		color: 0xbbc9c1,
		type: 'alloy',
		tier: 2,
		itemParts: ['plate', 'gear', 'plating', 'dust', 'rod'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_duralumin',
		amount: 4,
		dust_input: ['3x #forge:dusts/aluminum', '#forge:dusts/copper'],
		ingot_input: ['3x #forge:ingots/aluminum', '#forge:ingots/copper'],
		tinkers_input: [
			{ tag: 'forge:molten_aluminum', amount: 270 },
			{ tag: 'forge:molten_copper', amount: 90 },
		],
		allomancy: '与其他金属共同使用，增强其他金属的效果，如果硬铝消耗完毕，则会同时清空正在使用的金属',
		feruchemy: '联系 - 存储精神  抽取：村庄英雄  存储：不祥之兆',
	},
	{
		material: 'cobalt_brass',
		ore_name: '钴黄铜',
		color: 0xb8af98,
		type: 'alloy',
		tier: 2,
		itemParts: ['ingot', 'dust', 'nugget', 'plate', 'gear', 'rod'],
		blockParts: ['storage_block', 'casing', 'cog_block'],
		amount: 6,
		dust_input: [
			'4x #forge:dusts/brass',
			'#forge:dusts/aluminum',
			'#forge:dusts/cobalt',
		],
		ingot_input: [
			'4x #forge:ingots/brass',
			'#forge:ingots/aluminum',
			'#forge:ingots/cobalt',
		],
		tinkers_input: [
			{ tag: 'forge:molten_brass', amount: 360 },
			{ tag: 'forge:molten_aluminum', amount: 90 },
			{ tag: 'forge:molten_cobalt', amount: 90 },
		],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_cobalt_brass',
	},
	{
		material: 'energized_steel',
		ore_name: '充能钢',
		color: 0xe0d07e,
		type: 'alloy',
		tier: 2,
		itemParts: ['plate', 'rod', 'gear', 'sheet', 'dust'],
		blockParts: [],
	},
	{
		material: 'reinforced_electrum',
		ore_name: '高强琥珀金',
		color: 0x9c6097,
		type: 'alloy',
		tier: 2,
		itemParts: ['ingot', 'dust', 'nugget', 'plate', 'gear', 'rod'],
		blockParts: ['storage_block', 'scaffolding'],
		amount: 2,
		dust_input: ['2x #forge:dusts/electrum', '#forge:dusts/cobalt'],
		ingot_input: ['2x #forge:ingots/electrum', '#forge:ingots/cobalt'],
		tinkers_input: [
			{ tag: 'forge:molten_electrum', amount: 180 },
			{ tag: 'forge:molten_cobalt', amount: 90 },
		],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_reinforced_electrum',
	},
	/////////////// Tier 3 Alloys: Arc Furnace or chapter 3 /////////////////////////////

	{
		material: 'white_alloy',
		ore_name: '镁银合金',
		color: 0xe9f1f5,
		type: 'alloy',
		tier: 3,
		itemParts: [
			'ingot',
			'dust',
			'nugget',
			'plate',
			'sheet',
			'wire',
			'model_spool',
			'model_wire_coil',
		],
		blockParts: ['storage_block', 'coil'],
		amount: 3,
		dust_input: [
			'2x #forge:dusts/silver',
			'#forge:dusts/magnesium',
			'#forge:dusts/quartz',
		],
		ingot_input: [
			'2x #forge:ingots/silver',
			'#forge:ingots/magnesium',
			'#forge:gems/quartz',
		],
		tinkers_input: [
			{ tag: 'forge:molten_silver', amount: 180 },
			{ tag: 'forge:molten_magnesium', amount: 90 },
			{ tag: 'tconstruct:molten_quartz', amount: 100 },
		],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_white_alloy',
	},
	{
		material: 'compressed_steel',
		ore_name: '压缩钢',
		color: 0x6b6b6b,
		type: 'alloy',
		tier: 3,
		itemParts: ['dust', 'plate', 'rod', 'component', 'sheet'],
		blockParts: ['sheetmetal'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_compressed_steel',
	},
	{
		material: 'pressurized_aluminum_alloy',
		ore_name: '加压铝合金',
		color: 0xc8e0e0,
		type: 'alloy',
		tier: 3,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_pressurized_aluminum_alloy',
	},
	{
		material: 'netherite',
		ore_name: '下界合金',
		color: 0x524c49,
		type: 'alloy',
		tier: 3,
		itemParts: [],
		blockParts: [],
		amount: 1,
		dust_input: ['4x #forge:ingots/netherite_scrap', '4x #forge:dusts/gold'],
		ingot_input: ['4x #forge:ingots/netherite_scrap', '4x #forge:ingots/gold'],
	},
	{
		material: 'nethersteel',
		ore_name: '下界钢',
		color: 0x403836,
		type: 'alloy',
		tier: 3,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'plating'],
		blockParts: ['storage_block'],
		amount: 8,
		dust_input: ['8x #forge:dusts/steel', '#forge:ingots/netherite_scrap'],
		ingot_input: ['8x #forge:ingots/steel', '#forge:ingots/netherite_scrap'],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_nethersteel',
	},
	{
		material: 'industrial_alloy',
		ore_name: '工业合金',
		color: 0x574735,
		type: 'alloy',
		tier: 3,
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'gear',
			'rod',
			'plating',
			'component',
		],
		blockParts: ['storage_block'],
		//'amount': 8,
		//'dust_input': ['1x #forge:ingots/netherite_scrap','4x #forge:dusts/steel'],
		//'ingot_input': ['1x #forge:ingots/netherite_scrap','4x #forge:ingots/steel'],
	},
	{
		material: 'fluix_steel',
		ore_name: '福鲁伊克斯钢',
		color: 0x7e5fb0,
		type: 'alloy',
		tier: 3,
		itemParts: ['dust', 'plate', 'gear', 'rod', 'wire'],
		blockParts: ['storage_block'],
		fluid: 'thick',
		amount: 1,
		dust_input: ['#forge:dusts/steel', '2x lazierae2:carbonic_fluix_dust'],
		ingot_input: ['#forge:ingots/steel', '2x lazierae2:carbonic_fluix_dust'],
	},
	{
		material: 'lumium',
		ore_name: '流明',
		color: 0xffd894,
		type: 'alloy',
		tier: 3,
		itemParts: ['rod', 'base_ingot', 'base_dust'],
		blockParts: [],
		type: 'alloy',
		fluid_id: 'tconstruct:molten_lumium',
		//'amount': 2,
		//'dust_input': ['#forge:dusts/aluminum','#forge:dusts/electrum','2x #forge:dusts/glowstone'],
		//'ingot_input': ['#forge:ingots/aluminum','#forge:ingots/electrum','2x #forge:dusts/glowstone'],
	},
	{
		material: 'signalum',
		ore_name: '信素',
		color: 0xff6e4a,
		tier: 3,
		itemParts: ['rod'],
		blockParts: ['scaffolding'],
		type: 'alloy',
		fluid_id: 'tconstruct:molten_signalum',
		//'amount': 4,
		//'dust_input': ['3x #forge:dusts/bronze','#forge:dusts/silver','4x #forge:dusts/redstone'],
		//'ingot_input': ['3x #forge:ingots/bronze','#forge:ingots/silver','4x #forge:dusts/redstone'],
	},
	{
		material: 'enderium',
		ore_name: '末影',
		color: 0x5fc4d4,
		tier: 3,
		itemParts: ['rod', 'plating', 'hull_panel'],
		blockParts: [],
		type: 'alloy',
		fluid_id: 'tconstruct:molten_enderium',
		//'amount': 3,
		//'dust_input': ['2x #forge:dusts/pewter','#forge:dusts/platinum', '#forge:dusts/tungsten','2x minecraft:ender_pearl'],
		//'ingot_input': ['2x #forge:ingots/pewter','#forge:ingots/platinum', '#forge:ingots/tungsten','2x minecraft:ender_pearl'],
	},
	{
		material: 'arcane_gold',
		ore_name: '秘金',
		color: 0xe8a02a,
		type: 'alloy',
		tier: 3,
		itemParts: ['plate', 'gear', 'rod', 'dust'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_arcane_gold',
		amount: 1,
		dust_input: [
			'#forge:dusts/auric_gold',
			'#forge:gems/luminite',
			'2x #forge:dusts/arcane_crystal',
			'2x #forge:dusts/mundabitur',
		],
	},
	{
		material: 'manyullyn',
		ore_name: '玛玉灵',
		color: 0x8b68ad,
		type: 'alloy',
		tier: 3,
		itemParts: ['dust', 'plate', 'gear', 'rod'],
		blockParts: [],
		fluid_id: 'tconstruct:molten_manyullyn',
		amount: 4,
		dust_input: ['3x #forge:dusts/cobalt', '#forge:ingots/netherite_scrap'],
		ingot_input: ['3x #forge:ingots/cobalt', '#forge:ingots/netherite_scrap'],
	},

	{
		material: 'soulsteel',
		ore_name: '魂钢',
		color: 0x5c544d,
		type: 'alloy',
		tier: 3,
		itemParts: ['plate', 'rod', 'gear'],
		blockParts: [],
		//'amount': 3,
		//'dust_input': ['2x #forge:dusts/manyullyn', '#forge:dusts/titanium', '#forge:gems/uraninite'],
		//'ingot_input': ['2x #forge:ingots/manyullyn', '#forge:ingots/titanium', '#forge:gems/uraninite'],
		fluid_id: 'tconstruct:molten_soulsteel',
	},

	{
		material: 'titanite',
		ore_name: '榍石',
		color: 0x9754d1,
		type: 'alloy',
		tier: 3,
		itemParts: [
			'ingot',
			'dust',
			'nugget',
			'plate',
			'rod',
			'gear',
			'interlocking_component',
			'wire',
			'plating',
			'bolt',
			'hull_panel',
		],
		blockParts: ['storage_block', 'scaffolding', 'hull_casing', 'frame_box'],
		amount: 3,
		dust_input: [
			'2x #forge:dusts/manyullyn',
			'#forge:dusts/titanium',
			'#forge:gems/uraninite',
		],
		ingot_input: [
			'2x #forge:ingots/manyullyn',
			'#forge:ingots/titanium',
			'#forge:gems/uraninite',
		],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_titanite',
	},
	{
		material: 'swift_alloy',
		ore_name: '迅金',
		color: 0xf2c45a,
		type: 'alloy',
		tier: 3,
		itemParts: ['dust', 'plate', 'gear', 'rod'],
		blockParts: [],
		//'fluid_id': 'tconstruct:molten_manyullyn',
		//'amount': 4,
		//'dust_input': ['3x #forge:dusts/cobalt','#forge:ingots/netherite_scrap'],
		//'ingot_input': ['3x #forge:ingots/cobalt','#forge:ingots/netherite_scrap'],
	},

	/////////////// Tier 4 Alloys Mixer Only or chapter 4 /////////////////////////////

	{
		material: 'aerospace_alloy',
		ore_name: '航空合金',
		color: 0xe3feff,
		type: 'alloy',
		tier: 4,
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'gear',
			'rod',
			'plating',
			'model_rocket_nose_cone',
			'rocket_fin',
		],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_aerospace_alloy',
		fluid: 'thick',
		amount: 5,
		dust_input: [
			'3x #forge:dusts/pressurized_aluminum_alloy',
			'#forge:dusts/titanium',
			'#forge:dusts/chromium',
			'#forge:dusts/tier_2_mechanical_alloy',
		],
		ingot_input: [
			'3x #forge:ingots/pressurized_aluminum_alloy',
			'#forge:ingots/titanium',
			'#forge:ingots/chromium',
			'#forge:ingots/tier_2_mechanical_alloy',
		],
	},
	{
		material: 'chemically_inert_alloy',
		ore_name: '化学惰性合金',
		color: 0xa5afb0,
		type: 'alloy',
		tier: 4,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_chemically_inert_alloy',
		fluid: 'thick',
		amount: 3,
		dust_input: [
			'3x #forge:dusts/osmium',
			'#forge:dusts/white_alloy',
			'pneumaticcraft:plastic',
		],
		ingot_input: [
			'3x #forge:ingots/osmium',
			'#forge:ingots/white_alloy',
			'pneumaticcraft:plastic',
		],
	},
	{
		material: 'lunar_alloy',
		ore_name: '明月合金',
		color: 0xebb250,
		type: 'alloy',
		tier: 4,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'plating'],
		blockParts: ['storage_block'],
		amount: 3,
		dust_input: [
			'2x #forge:dusts/desh',
			'2x beyond_earth:cheese',
			'4x beyond_earth:moon_stone',
		],
		ingot_input: [
			'2x #forge:ingots/desh',
			'2x beyond_earth:cheese',
			'4x beyond_earth:moon_stone',
		],
	},
	{
		material: 'damascus_steel',
		ore_name: '大马士革钢',
		color: 0x828282,
		type: 'alloy',
		tier: 4,
		itemParts: ['custom_ingot', 'nugget', 'plate', 'gear', 'rod'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_damascus_steel',
		fluid: 'thick',
	},
	{
		material: 'bendalloy',
		ore_name: '弯管合金',
		color: 0xbab6a2,
		type: 'alloy',
		tier: 4,
		itemParts: ['plate', 'gear', 'dust', 'rod'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_bendalloy',
		amount: 3,
		dust_input: ['2x #forge:dusts/cadmium', '#forge:dusts/lead'],
		ingot_input: ['2x #forge:ingots/cadmium', '#forge:ingots/lead'],
		tinkers_input: [
			{ tag: 'forge:molten_cadmium', amount: 180 },
			{ tag: 'forge:molten_lead', amount: 90 },
		],
		allomancy: '加速玩家周围熔炉烧炼，植物生长等',
		feruchemy: '吞蚀 - 存储营养  抽取：给予饱和效果/补满饥饿条  抽取：减少饥饿条',
	},
	{
		material: 'nicrosil',
		ore_name: '镍铬',
		color: 0xa9a9b0,
		type: 'alloy',
		tier: 4,
		itemParts: ['plate', 'gear', 'dust', 'rod'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_nicrosil',
		amount: 4,
		dust_input: ['3x #forge:dusts/chromium', '#forge:dusts/iron'],
		ingot_input: ['3x #forge:ingots/chromium', '#forge:ingots/iron'],
		tinkers_input: [
			{ tag: 'forge:molten_chromium', amount: 270 },
			{ tag: 'forge:molten_iron', amount: 90 },
		],
		allomancy: '激活后点击其他玩家，增强其正在使用的金属并加速消耗，当停止增强时，清除其加速金属的所有单位',
		feruchemy: '承魂 - 存储神能  这种金属用于存储任何属性（但整个过程中有一定损失），然后可被用于抽取出任何属性。注意在抽取的过程中其他金属所存储的属性会流失',
	},
	{
		material: 'advanced_battery_alloy',
		ore_name: '高级能源合金',
		color: 0x6aa1d4,
		type: 'alloy',
		tier: 4,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'plating'],
		blockParts: ['storage_block'],
		amount: 3,
		dust_input: ['2x #forge:dusts/platinum', '#forge:dusts/cadmium'],
		ingot_input: ['2x #forge:ingots/platinum', '#forge:dusts/cadmium'],
	},

	/////////////// Tier 5 Alloys /////////////////////////////
	{
		material: 'fireite',
		ore_name: '火焰合金',
		color: 0x4a1304,
		tier: 5,
		itemParts: ['dust', 'plate', 'gear', 'rod'],
		blockParts: [],
		type: 'alloy',
	},
	{
		material: 'stainless_steel',
		ore_name: '不锈钢',
		color: 0xcedadb,
		type: 'alloy',
		tier: 5,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block', 'scaffolding'],
		fluid_id: 'kubejs:molten_stainless_steel',
		fluid: 'thick',
		amount: 9,
		dust_input: [
			'4x #forge:dusts/steel',
			'3x #forge:dusts/invar',
			'#forge:dusts/chromium',
			'#forge:dusts/manganese',
		],
		ingot_input: [
			'4x #forge:ingots/steel',
			'3x #forge:ingots/invar',
			'#forge:ingots/chromium',
			'#forge:ingots/manganese',
		],
	},
	{
		material: 'inconel',
		ore_name: '镍铬基合金',
		color: 0x484e5e,
		type: 'alloy',
		tier: 5,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_inconel',
		fluid: 'thick',
		amount: 7,
		dust_input: [
			'3x #forge:dusts/nickel',
			'2x #forge:dusts/cobalt',
			'#forge:dusts/chromium',
			'#forge:dusts/molybdenum',
		],
		ingot_input: [
			'3x #forge:ingots/nickel',
			'2x #forge:ingots/cobalt',
			'#forge:ingots/chromium',
			'#forge:ingots/molybdenum',
		],
	},
	{
		material: 'promethium',
		ore_name: '钷',
		color: 0x541f11,
		type: 'alloy',
		tier: 5,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_promethium',
		fluid: 'thick',
		amount: 4,
		dust_input: [
			'4x #forge:dusts/titanium',
			'#forge:dusts/fireite',
			'#forge:dusts/molybdenum',
			'4x kubejs:pyrotheum_dust',
		],
		ingot_input: [
			'4x #forge:ingots/titanium',
			'#forge:ingots/fireite',
			'#forge:ingots/molybdenum',
			'4x kubejs:pyrotheum_dust',
		],
	},

	/////////////// Tier 6 Alloys /////////////////////////////
	{
		material: 'adamantine_alloy',
		ore_name: '精金合金',
		color: 0xd1193b,
		type: 'alloy',
		tier: 6,
		itemParts: ['ingot', 'nugget', 'dust', 'plate', 'gear', 'rod', 'plating'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_adamantine_alloy',
		fluid: 'thick',
		amount: 3,
		dust_input: [
			'3x #forge:dusts/adamantium',
			'#forge:dusts/energetic_alloy',
			'#forge:dusts/manasteel',
		],
		ingot_input: [
			'3x #forge:ingots/adamantium',
			'#forge:ingots/energetic_alloy',
			'#forge:ingots/manasteel',
		],
	},
	{
		material: 'exoskeleton_composit',
		ore_name: '外骨骼',
		color: 0x9c845a,
		type: 'alloy',
		tier: 6,
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'plating',
			'reinforced_plating',
			'hull_panel',
		],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_exoskeleton_composit',
		fluid: 'thick',
		//'amount': 3,
		//'dust_input': ['3x #forge:dusts/adamantine_alloy','#forge:dusts/promethium','chemlib:chitin_dust'],
		//'ingot_input': ['3x #forge:ingots/adamantine_alloy','#forge:ingots/promethium', 'chemlib:chitin_dust'],
	},

	/////////////// Ore /////////////////////////////
	/*
	{
	  'material': 'rutile',
		ore_name: '金红石',
	  'color': 0xff4d4d,
	  'type': 'base_metal',
	  'itemParts': ['dust'],
	  'blockParts': [],
	  'ore': true
	},
	{
	  'material': 'sphalerite',
		ore_name: '闪锌矿',
	  'color': 0x7b7db0,
	  'type': 'base_metal',
	  'itemParts': ['dust'],
	  'blockParts': [],potent
	  'ore': true
	},*/
	///////////////////////// Thermogenic //////////////////////////////////////
	{
		material: 'imortite',
		ore_name: '不朽石',
		color: 0xf28a2e,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'copper',
			'zinc',
			'nickel',
			'uranium',
			'platinum',
			'orichalcum',
			'adamantium',
			'vibranium',
			'draconium',
		],
		gem_components: ['sulfur', 'fluorite'],
		byproducts: ['imortite', 'potentium'],
	},
	{
		material: 'potentium',
		ore_name: '蕴能素',
		color: 0xba49e3,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'gold',
			'zinc',
			'mithril',
			'rune',
			'desh',
			'orichalcum',
			'calorite',
			'vibranium',
			'draconium',
		],
		gem_components: ['diamond', 'amethyst'],
		byproducts: ['potentium', 'kharaxium'],
	},
	{
		material: 'kharaxium',
		ore_name: '哈克斯',
		color: 0x8f0000,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'iron',
			'arcanite',
			'aluminum',
			'magnesium',
			'cadmium',
			'ostrum',
			'adamantium',
			'vibranium',
			'draconium',
		],
		gem_components: ['ruby', 'cinnabar'],
		byproducts: ['kharaxium', 'imortite'],
	},

	{
		material: 'thermogenic',
		ore_name: '致热金属',
		color: 0xf06330,
		tier: 3,
		type: 'compound_rare_metal',
		itemParts: ['dust', 'shard'],
		blockParts: [],
		fluid: 'thick',
		components: ['uranium', 'chromium', 'magnesium', 'oxygen'],
		amount: 1,
		dust_input: [
			'#forge:ores/chunk/kharaxium',
			'#forge:ores/chunk/potentium',
			'#forge:ores/chunk/imortite',
		],
		ore: true,
	},
	//////////////////////// Thermolytic /////////////////////////
	{
		material: 'vincyte',
		ore_name: '文赛特',
		color: 0x0046d1,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'copper',
			'arcanite',
			'cobalt',
			'titanium',
			'platinum',
			'tungsten',
			'iridium',
			'uru',
			'draconium',
		],
		gem_components: ['lapis', 'apatite'],
		byproducts: ['vincyte', 'densite'],
	},
	{
		material: 'densite',
		ore_name: '密度',
		color: 0x667e94,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'tin',
			'silver',
			'aluminum',
			'magnesium',
			'osmium',
			'ostrum',
			'iridium',
			'uru',
			'draconium',
		],
		gem_components: ['quartz', 'certus_quartz'],
		byproducts: ['densite', 'jimmium'],
	},
	{
		material: 'jimmium',
		ore_name: '吉姆',
		color: 0x270059,
		tier: 1,
		type: 'compound_ore',
		itemParts: ['dust', 'ingot'],
		blockParts: [],
		fluid: 'thick',
		ore: true,
		raw_ore: true,
		components: [
			'iron',
			'lead',
			'nickel',
			'titanium',
			'osmium',
			'tungsten',
			'calorite',
			'uru',
			'draconium',
		],
		gem_components: ['emerald', 'niter'],
		byproducts: ['jimmium', 'vincyte'],
	},
	{
		material: 'thermolytic',
		ore_name: '热解',
		color: 0x42f5da,
		tier: 3,
		type: 'compound_rare_metal',
		itemParts: ['dust', 'shard'],
		blockParts: [],
		fluid: 'thick',
		components: ['titanium', 'manganese', 'thorium', 'hydrogen'],
		amount: 1,
		dust_input: [
			'#forge:ores/chunk/jimmium',
			'#forge:ores/chunk/densite',
			'#forge:ores/chunk/vincyte',
		],
		ore: true,
	},

	/////////////// CUSTOM ALLOYS /////////////////////////////
	{
		material: 'tier_1_mechanical_alloy',
		ore_name: '1级机械合金',
		color: 0xcbe848,
		type: 'alloy',
		tier: 1,
		iconset: 'mechanical',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'gear',
			'interlocking_component',
			'rod',
			'model_robot_arm',
			'wire',
		],
		blockParts: ['storage_block', 'cog_block'],
		fluid_id: 'kubejs:molten_tier_1_mechanical_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/tin',
			'#forge:dusts/zinc',
			['ars_nouveau:air_essence', 'elementalcraft:powerful_air_shard'],
		],
		ingot_input: [
			'3x #forge:ingots/tin',
			'#forge:ingots/zinc',
			['ars_nouveau:air_essence', 'elementalcraft:powerful_air_shard'],
		],
	},
	{
		material: 'tier_1_electrical_alloy',
		ore_name: '1级电力合金',
		color: 0xf0963c,
		type: 'alloy',
		tier: 1,
		iconset: 'electrical',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'wire',
			'model_spool',
			'model_wire_coil',
			'sheet',
			'model_dual_coil',
		],
		blockParts: ['storage_block', 'coil'],
		fluid_id: 'kubejs:molten_tier_1_electrical_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/gold',
			'#forge:dusts/silver',
			['ars_nouveau:fire_essence', 'elementalcraft:powerful_fire_shard'],
		],
		ingot_input: [
			'3x #forge:ingots/gold',
			'#forge:ingots/silver',
			['ars_nouveau:fire_essence', 'elementalcraft:powerful_fire_shard'],
		],
	},
	{
		material: 'tier_1_magical_alloy',
		ore_name: '1级魔法合金',
		color: 0x9383c7,
		type: 'alloy',
		tier: 1,
		iconset: 'magical',
		itemParts: ['ingot', 'nugget', 'dust', 'rod', 'ring', 'sprocket'],
		blockParts: ['storage_block'],
		fluid_id: 'kubejs:molten_tier_1_magical_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/copper',
			'#forge:dusts/drenched_iron',
			['ars_nouveau:water_essence', 'elementalcraft:powerful_water_shard'],
		],
		ingot_input: [
			'3x #forge:ingots/copper',
			'#forge:ingots/drenched_iron',
			['ars_nouveau:water_essence', 'elementalcraft:powerful_water_shard'],
		],
	},
	{
		material: 'tier_1_structural_alloy',
		ore_name: '1级结构合金',
		color: 0x76b090,
		type: 'alloy',
		tier: 1,
		iconset: 'structural',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'rod',
			'plating',
			'reinforced_plating',
			'hull_panel',
			'bolt',
			'sheetmetal',
		],
		blockParts: ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box'],
		fluid_id: 'kubejs:molten_tier_1_structural_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/iron',
			'#forge:dusts/lead',
			['ars_nouveau:earth_essence', 'elementalcraft:powerful_earth_shard'],
		],
		ingot_input: [
			'3x #forge:ingots/iron',
			'#forge:ingots/lead',
			['ars_nouveau:earth_essence', 'elementalcraft:powerful_earth_shard'],
		],
	},
	{
		material: 'tier_2_mechanical_alloy',
		ore_name: '2级机械合金',
		color: 0xe8e348,
		type: 'alloy',
		tier: 2,
		iconset: 'mechanical',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'gear',
			'interlocking_component',
			'rod',
			'model_robot_arm',
			'wire',
		],
		blockParts: ['storage_block', 'cog_block'],
		fluid_id: 'kubejs:molten_tier_2_mechanical_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/tier_1_mechanical_alloy',
			'#forge:dusts/aluminum',
			'#forge:dusts/cobalt',
			'create:precision_mechanism',
		],
		ingot_input: [
			'3x #forge:ingots/tier_1_mechanical_alloy',
			'#forge:ingots/aluminum',
			'#forge:ingots/cobalt',
			'create:precision_mechanism',
		],
	},
	{
		material: 'tier_2_electrical_alloy',
		ore_name: '2级电力合金',
		color: 0xf09169,
		type: 'alloy',
		tier: 4,
		iconset: 'electrical',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'wire',
			'model_spool',
			'model_wire_coil',
			'sheet',
			'model_dual_coil',
		],
		blockParts: ['storage_block', 'coil'],
		fluid_id: 'kubejs:molten_tier_2_electrical_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/tier_1_electrical_alloy',
			'#forge:dusts/platinum',
			'#forge:dusts/cadmium',
			'immersiveengineering:component_electronic',
		],
		ingot_input: [
			'3x #forge:ingots/tier_1_electrical_alloy',
			'#forge:ingots/platinum',
			'#forge:ingots/cadmium',
			'immersiveengineering:component_electronic',
		],
	},
	{
		material: 'tier_2_structural_alloy',
		ore_name: '2级结构合金',
		color: 0x39ccc2,
		type: 'alloy',
		tier: 2,
		iconset: 'structural',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'rod',
			'plating',
			'reinforced_plating',
			'hull_panel',
			'bolt',
			'sheetmetal',
		],
		blockParts: ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box'],
		fluid_id: 'kubejs:molten_tier_2_structural_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/tier_1_structural_alloy',
			'2x #forge:dusts/nickel',
			'#forge:dusts/steel',
		],
		ingot_input: [
			'3x #forge:ingots/tier_1_structural_alloy',
			'2x #forge:ingots/nickel',
			'#forge:ingots/steel',
		],
	},
	{
		material: 'tier_3_structural_alloy',
		ore_name: '3级结构合金',
		color: 0x3296e3,
		type: 'alloy',
		tier: 5,
		iconset: 'structural',
		itemParts: [
			'ingot',
			'nugget',
			'dust',
			'plate',
			'rod',
			'plating',
			'reinforced_plating',
			'hull_panel',
			'bolt',
			'sheetmetal',
		],
		blockParts: ['storage_block', 'casing', 'scaffolding', 'hull_casing', 'frame_box'],
		fluid_id: 'kubejs:molten_tier_3_structural_alloy',
		fluid: 'thick',
		amount: 2,
		dust_input: [
			'3x #forge:dusts/tier_2_structural_alloy',
			'2x #forge:dusts/tungsten',
			'mekanism:hdpe_sheet',
		],
		ingot_input: [
			'3x #forge:ingots/tier_2_structural_alloy',
			'2x #forge:ingots/tungsten',
			'mekanism:hdpe_sheet',
		],
	},

	/////////////// Other /////////////////////////////
	{
		material: 'slag',
		ore_name: '炉渣',
		color: 0x947b6c,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'crystal_slag',
		ore_name: '炉渣水晶',
		color: 0xb1d15a,
		type: 'gem',
		itemParts: ['gem', 'dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'rich_slag',
		ore_name: '富炉渣',
		color: 0x8a472d,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'end_stone',
		ore_name: '末地石',
		color: 0xebe596,
		type: 'stone',
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	//{
	//  'material': 'netherrack',
	// ore_name: '下界岩',
	//  'color': 0x611324,
	//  'type': 'stone',
	//  'itemParts': ['dust'],
	//  'blockParts': [],
	//  'fluid': 'thick'
	//},
	{
		material: 'wood',
		ore_name: '木',
		color: 0x825c45,
		itemParts: [],
		blockParts: ['scaffolding'],
	},
	{
		material: 'ancient_wood',
		ore_name: '远古木',
		color: 0xa86cba,
		itemParts: [],
		blockParts: ['scaffolding'],
	},
	{
		material: 'redstone',
		ore_name: '红石',
		color: 0xf54242,
		type: 'dust',
		tier: 1,
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'sulfur',
		ore_name: '硫磺',
		color: 0xe1eb34,
		type: 'gem',
		iconset: 'sulfur',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'luminite',
		ore_name: '夜明',
		color: 0xffed7a,
		type: 'gem',
		iconset: 'sapphire',
		itemParts: ['gem', 'dust'],
		blockParts: ['storage_block'],
		ore: true,
		burnTime: 16, //items * 200
		fluid: 'thick',
	},
	{
		material: 'manasteel',
		ore_name: '魔力钢',
		color: 0x69a7ff,
		type: 'magic_alloy',
		tier: 2,
		itemParts: ['dust', 'plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
		fluid_id: 'kubejs:molten_manasteel',
	},
	{
		material: 'terrasteel',
		ore_name: '泰拉钢',
		color: 0x63e645,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'elementium',
		ore_name: '源质钢',
		color: 0xf569b6,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'transmuted_silver',
		ore_name: '嬗变银',
		color: 0xa9d0d9,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
	},
	{
		material: 'infused_iron',
		ore_name: '灌注铁',
		color: 0x54b33b,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: [],
	},
	{
		material: 'tainted_gold',
		ore_name: '污染黄金',
		color: 0xa66032,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod', 'dust'],
		blockParts: [],
	},
	{
		material: 'sky_metal',
		ore_name: '天空金属',
		color: 0x83d5de,
		type: 'magic_alloy',
		itemParts: ['plate', 'gear', 'rod'],
		blockParts: ['storage_block'],
	},
	{
		material: 'air',
		ore_name: '气元素',
		color: 0xfcffbf,
		type: 'element',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'earth',
		ore_name: '地元素',
		color: 0x579c4e,
		type: 'element',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'fire',
		ore_name: '火元素',
		color: 0xe34536,
		type: 'element',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'water',
		ore_name: '水元素',
		color: 0x4272f5,
		type: 'element',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'plutonium',
		ore_name: '钚',
		color: 0xbdabff,
		itemParts: ['ingot', 'nugget', 'dust'],
		blockParts: ['storage_block'],
		fluid: 'thick',
	},
	{
		material: 'neptunium',
		ore_name: '海王',
		color: 0x5a5863,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'americium',
		ore_name: '镅',
		color: 0x4a3a2f,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'curium',
		ore_name: '锔',
		color: 0x8a3e50,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'berkelium',
		ore_name: '锫',
		color: 0x755444,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'californium',
		ore_name: '锎',
		color: 0xc93328,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},
	{
		material: 'einsteinium',
		ore_name: '锿',
		color: 0x4a6da8,
		itemParts: ['dust'],
		blockParts: [],
		fluid: 'thick',
	},

	{
		material: 'aerotheum',
		ore_name: '空气',
		color: 0xaea87c,
		tier: 3,
		type: 'alloy',
		itemParts: ['custom_dust'],
		blockParts: [],
		dust_input: [
			'thermal:blitz_powder',
			'#forge:dusts/glowstone',
			'cloudstorage:static_cloud',
			'ars_nouveau:air_essence',
		],
		amount: 2,
	},
	{
		material: 'cryotheum',
		ore_name: '凛冰',
		color: 0x1fd0fa,
		tier: 3,
		type: 'alloy',
		itemParts: ['custom_dust'],
		blockParts: [],
		dust_input: [
			'thermal:blizz_powder',
			'#forge:dusts/lapis',
			'powah:charged_snowball',
			'ars_nouveau:water_essence',
		],
		amount: 2,
	},
	{
		material: 'petrotheum',
		ore_name: '地岩',
		color: 0x221915,
		tier: 3,
		type: 'alloy',
		itemParts: ['custom_dust'],
		blockParts: [],
		dust_input: [
			'thermal:basalz_powder',
			'#forge:dusts/coal',
			'#forge:bitumen',
			'ars_nouveau:earth_essence',
		],
		amount: 2,
	},
	{
		material: 'pyrotheum',
		ore_name: '炽焱',
		color: 0xfda735,
		tier: 3,
		type: 'alloy',
		itemParts: ['custom_dust'],
		blockParts: [],
		dust_input: [
			'minecraft:blaze_powder',
			'#forge:dusts/redstone',
			'#forge:gems/sulfur',
			'ars_nouveau:fire_essence',
		],
		amount: 2,
	},
	{
		material: 'plastic',
		ore_name: '塑料',
		color: 0xe8e8e8,
		itemParts: [],
		blockParts: ['scaffolding'],
	},
	/*
	{
	  'material': 'blazing_redstone',
		ore_name: '烈焰红石',
	  'color': 0xd1482a,
	  'tier': 1,
	  'type': 'alloy',
	  'itemParts': ['custom_dust'],
	  'blockParts': [],
	  'dust_input': ['minecraft:blaze_powder','#forge:dusts/redstone'],
	  'amount': 1,
	},
	{
	  'material': 'refined_iron',
		ore_name: '精炼铁',
	  'color': 0xdbf5ff,
	  'type': 'alloy',
	  'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear', 'wire'],
	  'blockParts': ['storage_block'],
	  'fluid': 'thick',
	},
	{
	  'material': 'crude_steel',
		ore_name: '粗制钢',
	  'color': 0x6a7175,
	  'type': 'alloy',
	  'itemParts': ['ingot', 'nugget', 'dust', 'plate', 'gear',],
	  'blockParts': ['storage_block'],
	  'fluid': 'thick',
	},
	{
	  'material': 'thermalloy',
		ore_name: '',
	  'color': 0x8b4aed,
	  'type': 'alloy',
	  'tier': 1,
	  'itemParts': ['ingot', 'nugget', 'rod', 'dust', 'plate', 'gear', 'wire', 'interlocking_component'],
	  'blockParts': ['scaffolding','sheetmetal', 'cog_block','storage_block'],
	  'fluid': 'thick',
	  'fluid_id': 'kubejs:molten_thermalloy',
	  'amount': 3,
	  'dust_input': ['#forge:dusts/lumium','#forge:dusts/signalum','#forge:dusts/enderium'],
	  'ingot_input': ['#forge:ingots/lumium','#forge:ingots/signalum','#forge:ingots/enderium'],
	  'tinkers_input': [{tag: 'forge:molten_lumium',amount: 90},{tag: 'forge:molten_signalum',amount: 90},{tag: 'forge:molten_enderium',amount: 90}]
	},
	*/

	/////////////// Gems /////////////////////////////
	/*
	{
	  'material': 'ruby',
		ore_name: '红宝石',
	  'gem': true,
	  'color': 0xff4f55,
	  'type': 'gem',
	  'itemParts': ['ruby', 'dust'],
	  'blockParts': ['storage_block'],
	  'ore': true
	},
	{
	  'material': 'sapphire',
		ore_name: '蓝宝石',
	  'gem': true,
	  'color': 0x7377ff,
	  'type': 'gem',
	  'itemParts': ['sapphire', 'dust'],
	  'blockParts': ['storage_block'],
	  'ore': true
	}*/
	{
		material: 'certus_quartz',
		ore_name: '赛特斯石英',
		gem: true,
		color: 0xb7d8f7,
		type: 'gem',
		iconset: 'quartz',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'quartz',
		ore_name: '石英',
		gem: true,
		color: 0xfff5e8,
		type: 'gem',
		iconset: 'quartz',
		itemParts: [],
		blockParts: [],
		ore: true,
	},
	{
		material: 'diamond',
		ore_name: '钻石',
		gem: true,
		color: 0x42f5ef,
		type: 'gem',
		iconset: 'diamond',
		itemParts: [],
		blockParts: [],
		ore: false,
	},
	{
		material: 'emerald',
		ore_name: '绿宝石',
		gem: true,
		color: 0x12b525,
		type: 'gem',
		iconset: 'emerald',
		itemParts: [],
		blockParts: [],
		ore: false,
	},
]

global.stoneTypes = [
	{
		material: 'deepslate',
		ore_name: '深板岩',
		hardness: 6,
		resistance: 6,
	},
	{
		material: 'netherrack',
		ore_name: '下界岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'tuff',
		ore_name: '凝灰岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'smooth_basalt',
		ore_name: '平滑玄武岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'basalt',
		ore_name: '玄武岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'blackstone',
		ore_name: '黑石',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'end_stone',
		ore_name: '末地石',
		hardness: 4,
		resistance: 4,
	},
	{
		material: 'darkstone',
		ore_name: '暗黑石',
		hardness: 6,
		resistance: 6,
	},
	{
		material: 'bedrock',
		ore_name: '基岩',
		hardness: 10,
		resistance: 10,
	} /*
      {
        'material': 'soapstone',
		ore_name: '皂石',
        'hardness': 3,
        'resistance': 3
      },*/,
	{
		material: 'granite',
		ore_name: '花岗岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'diorite',
		ore_name: '闪长岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'andesite',
		ore_name: '安山岩',
		hardness: 3,
		resistance: 3,
	},
	{
		material: 'moon_stone',
		ore_name: '月石',
		hardness: 4,
		resistance: 4,
	},
	{
		material: 'mars_stone',
		ore_name: '火星石',
		hardness: 4,
		resistance: 4,
	},
	{
		material: 'venus_stone',
		ore_name: '金星石',
		hardness: 4,
		resistance: 4,
	},
	{
		material: 'glacio_stone',
		ore_name: '霜原石',
		hardness: 4,
		resistance: 4,
	},
]
